[package]
name = "weather-app"
version = "0.1.0"
edition = "2024"

[package.metadata.rust-analyzer] 
rustc_private=true

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking"] }
serde = "1.0.218"
